name: Prose Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install write-good
        run: npm install write-good

      - name: Run write-good
        id: write-good
        run: |
          output=$(write-good $(find . -name "*.md"))
          echo "::set-output name=output::$output"
        continue-on-error: true

      - name: Post write-good Comment
        if: steps.write-good.outcome != 'skipped' && steps.write-good.output != ''
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            write-good results:
            ```
            ${{ steps.write-good.output }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false

