name: Prose Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Prose Linting Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y proselint write-good

      - name: Run Proselint
        id: proselint
        run: |
          output=$(proselint $(find . -name "*.md"))
          echo "::set-output name=output::$output"
        continue-on-error: true

      - name: Run write-good
        id: write-good
        run: |
          output=$(write-good $(find . -name "*.md"))
          echo "::set-output name=output::$output"
        continue-on-error: true

      - name: Post Proselint Comment
        if: steps.proselint.outcome != 'skipped' && steps.proselint.output != ''
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Proselint results:
            ```
            ${{ steps.proselint.output }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false

      - name: Post write-good Comment
        if: steps.write-good.outcome != 'skipped' && steps.write-good.output != ''
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            write-good results:
            ```
            

